version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
